# Numpy

 - Numerical python
 - Fastest
 - vactorised operation
 - Contigous Memory

In [1]:
# create a numpy array 
import numpy as np

In [2]:
# creating an array using python list

x = np.array([22,44,32,44,56,54])
x

array([22, 44, 32, 44, 56, 54])

In [3]:
x.size

6

In [4]:
# 1d array = Vector
# 2d = Matrix
# 3d = Cube
# nd = .....
x.shape

(6,)

In [5]:
# to see the dimension of array
x.ndim

1

In [6]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr2d =np.array([[1,2,3],[11,22,33],[111,222,333],[1111,2222,3333]])
arr2d

array([[   1,    2,    3],
       [  11,   22,   33],
       [ 111,  222,  333],
       [1111, 2222, 3333]])

In [8]:
arr2d.ndim

2

In [9]:
arr2d.shape

(4, 3)

In [10]:
arr2d= np.arange(20).reshape(1,20)
# arr2d= np.arange(20).reshape(20,1)
# arr2d= np.arange(20).reshape(4,5)
# arr2d= np.arange(20).reshape(5,4)
# arr2d= np.arange(20).reshape(10,2)
# arr2d= np.arange(20).reshape(2,10)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [11]:
arr2d.ndim

2

In [12]:
arr2d.shape

(1, 20)

In [13]:
arr2d.reshape(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
arr2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
arr2d.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
# scaler 
arr = np.array(10)
arr

array(10)

In [17]:
arr.ndim

0

In [18]:
arr3d = np.arange(64).reshape(4,4,4) # (depth ,row ,colums)
                                    # (matrixnum ,row ,colums)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [19]:
arr3d.ndim

3

- Element access

In [20]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [21]:
arr2d[0,6]

6

In [22]:
arr2d[0][6]

6

In [23]:
arr3d[1]

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [24]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [25]:
arr3d[2,1,2]

38

In [26]:
x

array([22, 44, 32, 44, 56, 54])

In [27]:
z = []
for n in x:
    z.append(n*2)
z

[44, 88, 64, 88, 112, 108]

In [28]:
[n**2 for n in x]

[484, 1936, 1024, 1936, 3136, 2916]

- Vectorize operation

In [29]:
x*2

array([ 44,  88,  64,  88, 112, 108])

In [30]:
arr2d*5

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75,
        80, 85, 90, 95]])

In [31]:
arr3d*10

array([[[  0,  10,  20,  30],
        [ 40,  50,  60,  70],
        [ 80,  90, 100, 110],
        [120, 130, 140, 150]],

       [[160, 170, 180, 190],
        [200, 210, 220, 230],
        [240, 250, 260, 270],
        [280, 290, 300, 310]],

       [[320, 330, 340, 350],
        [360, 370, 380, 390],
        [400, 410, 420, 430],
        [440, 450, 460, 470]],

       [[480, 490, 500, 510],
        [520, 530, 540, 550],
        [560, 570, 580, 590],
        [600, 610, 620, 630]]])

In [32]:
# mirroring = elementwise operation
a = np.arange(25).reshape(5,5)
b = np.arange(25,50).reshape(5,5)

In [33]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
b

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [35]:
a +b

array([[25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43],
       [45, 47, 49, 51, 53],
       [55, 57, 59, 61, 63],
       [65, 67, 69, 71, 73]])

# Array Slicing

In [36]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
 a[2,3]

13

In [38]:
# array [row,col]
#       [start:end , start;end]

In [39]:
a[2:3 ,3:4]

array([[13]])

# Querrying Array

In [40]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
mask = a>5  # Mask
mask

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [42]:
a[mask]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [43]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
a[a>9] =25
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25]])

In [45]:
np.where(a>13,35,a)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [35, 35, 35, 35, 35],
       [35, 35, 35, 35, 35],
       [35, 35, 35, 35, 35]])

# Combining Arrays

In [49]:
print(a)
a.shape

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [25 25 25 25 25]
 [25 25 25 25 25]
 [25 25 25 25 25]]


(5, 5)

In [51]:
print(b)
b.shape

[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


(5, 5)

In [52]:
np.concatenate((a,b)) # axis is 0 so addin verticaly 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [53]:
np.concatenate((a,b),axis=1) 

array([[ 0,  1,  2,  3,  4, 25, 26, 27, 28, 29],
       [ 5,  6,  7,  8,  9, 30, 31, 32, 33, 34],
       [25, 25, 25, 25, 25, 35, 36, 37, 38, 39],
       [25, 25, 25, 25, 25, 40, 41, 42, 43, 44],
       [25, 25, 25, 25, 25, 45, 46, 47, 48, 49]])

In [54]:
np.stack((a,b))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [25, 25, 25, 25, 25],
        [25, 25, 25, 25, 25],
        [25, 25, 25, 25, 25]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [55]:
np.hstack((a,b))

array([[ 0,  1,  2,  3,  4, 25, 26, 27, 28, 29],
       [ 5,  6,  7,  8,  9, 30, 31, 32, 33, 34],
       [25, 25, 25, 25, 25, 35, 36, 37, 38, 39],
       [25, 25, 25, 25, 25, 40, 41, 42, 43, 44],
       [25, 25, 25, 25, 25, 45, 46, 47, 48, 49]])

In [56]:
np.vstack((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [63]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [64]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [65]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])