# Numpy Practice setion

In [2]:
import numpy as np

## creating array using numpy

In [3]:
#1-D array
food = np.array(["Pakora", "Samosa" ,"Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [4]:
price = np.array([5, 5, 5])
price

array([5, 5, 5])

In [5]:
type(price)

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [7]:
len(food)

3

In [8]:
len(price)

3

In [9]:
price[2]

5

In [10]:
price[0:]

array([5, 5, 5])

In [11]:
food[1]

'Samosa'

In [12]:
food[0:]

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [13]:
price.mean()

5.0

In [14]:
# Zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
# empty
np.empty(1)

array([5.4e-322])

In [21]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [26]:
# Specific interval
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
# Table of 5
np.arange(5 ,55 ,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [29]:
# line space
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [31]:
# Specify your data type
np.ones(50 ,dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [33]:
np.ones(50 ,dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array function

In [35]:
a = np.array([10,12,150,54,13,15,79,320,2.5,5.32,10.5])
a

array([ 10.  ,  12.  , 150.  ,  54.  ,  13.  ,  15.  ,  79.  , 320.  ,
         2.5 ,   5.32,  10.5 ])

In [37]:
a.sort()
a

array([  2.5 ,   5.32,  10.  ,  10.5 ,  12.  ,  13.  ,  15.  ,  54.  ,
        79.  , 150.  , 320.  ])

In [39]:
b = np.array([2.5, 103,15,45,97.1 ,46.5,489])
b

array([  2.5, 103. ,  15. ,  45. ,  97.1,  46.5, 489. ])

In [40]:
c = np.concatenate((a,b))
c

array([  2.5 ,   5.32,  10.  ,  10.5 ,  12.  ,  13.  ,  15.  ,  54.  ,
        79.  , 150.  , 320.  ,   2.5 , 103.  ,  15.  ,  45.  ,  97.1 ,
        46.5 , 489.  ])

In [41]:
c.sort()
c

array([  2.5 ,   2.5 ,   5.32,  10.  ,  10.5 ,  12.  ,  13.  ,  15.  ,
        15.  ,  45.  ,  46.5 ,  54.  ,  79.  ,  97.1 , 103.  , 150.  ,
       320.  , 489.  ])

# 2-D Array

In [42]:
a = np.array([[1,2,3,4,5],[5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [46]:
b = np.array([[6,7,8,8,9],[8,9,3,2,1]])
b

array([[6, 7, 8, 8, 9],
       [8, 9, 3, 2, 1]])

In [47]:
c = np.concatenate((a,b))
c

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [6, 7, 8, 8, 9],
       [8, 9, 3, 2, 1]])

In [49]:
c = np.concatenate((a,b), axis=1)
c

array([[1, 2, 3, 4, 5, 6, 7, 8, 8, 9],
       [5, 4, 3, 2, 1, 8, 9, 3, 2, 1]])

In [50]:
c.ndim

2

In [57]:
a = np.array([[[1,3,4],
               [4,4,5]],
              
              [[2,4,3],
               [7,6,4]],
              
              [[3,9,5],
               [2,3,4]]])
a

array([[[1, 3, 4],
        [4, 4, 5]],

       [[2, 4, 3],
        [7, 6, 4]],

       [[3, 9, 5],
        [2, 3, 4]]])

In [56]:
# To find the Number of dimention
a.ndim

3

In [58]:
# size mean number of element
a.size

18

In [60]:
# shape
a.shape

(3, 2, 3)

In [69]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
# reshape
a =a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
# reshape
np.reshape(a , newshape=(1, 9), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [73]:
# convert 1D into 2D
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
a.shape

(9,)

In [77]:
a.ndim

1

In [75]:
b = a[np.newaxis , :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [76]:
b.ndim

2

In [78]:
b.shape

(1, 9)

In [79]:
c = a[: ,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [80]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
a[3:7]

array([4, 5, 6, 7])

In [82]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [83]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [85]:
a.sum()

45

In [86]:
a.mean()

5.0